services: 
  server:
    container_name: server
    image: sha256:af0209507766dce39eddbb0f43e9e52337f91ca4a4aeff3ff0e30c4f30e8eab8
    build: .
    networks:
      - foxkids_network
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    volumes:
      - "./ssl/:/etc/nginx/ssl/"
      - "/opt/data/hls:/opt/data/hls"

networks:
  foxkids_network:
    driver: bridge
    name: foxkids_network

