version: "3"
services: 
  server:
    container_name: server
    image: zipkortnicks57/foxkids_online:nginx-server
    networks:
      - foxkids_network
    ports:
      - "81:80"
      - "444:443"
      - "1936:1935"
    volumes:
      - "/home/foxkids/foxkids-project/nginx/ssl/:/etc/nginx/ssl/"
      - "/opt/data/hls:/opt/data/hls"

networks:
  foxkids_network:
    driver: bridge

