services: 
  server:
    container_name: server
    # image: alfg/nginx-rtmp:latest
    build: .
    networks:
      - foxkids_network
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    volumes:
      # - "./nginx.conf:/etc/nginx/nginx.conf.template"
      - "/docker/foxkids/ssl/:/etc/nginx/ssl/"
      - "/opt/data/hls:/opt/data/hls"

networks:
  foxkids_network:
    driver: bridge
    name: foxkids_network

