version: "3"
services: 
  server:
    container_name: server
    image: zipkortnicks57/foxkids_online:nginx-server
    build: .
    networks:
      - foxkids_network
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - /opt/data/hls:/opt/data/hls

networks:
  foxkids_network:
    driver: bridge

