# Доставка на сервер

name: cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # позволяет ручной запуск
  workflow_dispatch:

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login into dockerhub
        run:  echo "${{ secrets.DOCKER_TOKEN }}" | docker login "${{ vars.DOCKER_PATH }}" -u "${{ vars.DOCKER_USER }}" --password-stdin

      - name: Build Image
        run: docker build . -t ${{ vars.DOCKER_REGISTRY }}:${{ vars.DOCKER_TAG }}
      
      - name: Publish Image
        run: docker push ${{ vars.DOCKER_REGISTRY }}:${{ vars.DOCKER_TAG }}
  deploy:
    name: deploy on stage
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ needs.build.result == 'success'}}
    steps:
      - name: install sshkeys
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa 
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa 
          ssh-keyscan -H ${{ vars.SSH_HOST }} > ~/.ssh/known_hosts  
      - name: check ssh
        run:
          ssh-keygen -l -f ~/.ssh/id_rsa
      - name: deploy
        run: |
          ssh -i ~/.ssh/id_rsa ${{ vars.SSH_USER}}@${{ vars.SSH_HOST }} "cd ${{ vars.WORKDIR }} && mkdir -p nginx &&
          cd nginx && mkdir -p ssl && echo "${{ secrets.SSL_CERT }}" > ssl/foxkids.online.crt && 
          echo "${{ secrets.SSL_KEY }}" > ssl/foxkids.online.key &&  
          curl https://raw.githubusercontent.com/zipkortnicks57/foxkids-nginx/refs/heads/${{ github.head_ref || github.ref_name }}/docker-compose.yml" 
      
