# Доставка на сервер

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # позволяет ручной запуск
  workflow_dispatch:

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Docker-compose installing
      #   run: |
      #     mkdir /usr/local/bin/docker-compose |
      #     curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose |
      #     chmod +x /usr/local/bin/docker-compose |
      #     docker compose version

      - name: Login into dockerhub
        run:  echo "${{ vars.DOCKER_TOKEN }}" | docker login "${{ vars.DOCKER_PATH }}" -u "${{ vars.DOCKER_USER }}" --password-stdin

      - name: Build Image
        run: docker build . -t ${{ vars.DOCKER_REGISTRY }}:${{ vars.DOCKER_TAG }}
      
      - name: Publish Image
        run: docker push ${{ vars.DOCKER_REGISTRY }}:${{ vars.DOCKER_TAG }}

      
