# Доставка на сервер

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # позволяет ручной запуск
  workflow_dispatch:

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build end send image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login "${{ secrets.DOCKER_PATH }}" -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin! |
          docker compose build . |
          docker compose image push "${{ secrets.DOCKER_USER }}"/"${{ secrets.DOCKER_FOLDER }}"
